spring.application.name=avis-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:avis_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update

# Config pour Feign
application.config.produit-service-url=http://produit-service:8081

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
